Dataset CRUD + Project List Functions
Datatamer/tamr-client pull request #452
Opened 2020-09-02 21:22 UTC by skalish

# ↪️ Pull Request

This PR closes the feature gap for Tamr dataset creation and deletion.  Additionally, it adds functionality to get the list of all datasets/projects on an instance (as `Dataset`/`Project` objects), optionally passing a filter.

## 💻 Examples

```python
import tamr_client as tc

session = ...
instance = ...

# Make a new dataset
new_dataset = tc.dataset.create(
    s,
    instance,
    name="My New Dataset",
    key_attribute_names=("primary_key",),
    description="A new dataset created with TC",
)
# Delete the dataset
tc.dataset.delete(s, new_dataset)

# Get all datasets
dataset_list = tc.dataset.get_all(s, instance)

# Get all projects
project_list = tc.project.get_all(s, instance)

# Get all datasets that match a filter
wobbly_dataset_list = tc.dataset.get_all(s, instance, filter="name==wobbly")
```

## ✔️ PR Todo

- [x] Added/updated testing for this change
- [ ] Included links to related issues/PRs
- [x] Update relevant [docs](https://github.com/Datatamer/tamr-client/tree/master/docs) + docstrings
- [ ] Update the [CHANGELOG](https://github.com/Datatamer/tamr-client/blob/master/CHANGELOG.md) under the current `-dev` version:
  - Add changelog entries under any that apply: **BREAKING CHANGES**, **NEW FEATURES**, **BUG FIXES**.
  - Changelog entry format: `[#<issue number>](<link to issue>) <change description>`

2020-09-02 21:28 UTC, skalish commented
The `POST /v1/datasets` creation API call returns a status `400` when trying to create a dataset with a name that is already in use, which makes handling this with an informative `dataset.AlreadyExists` exception difficult.

2020-09-02 21:33 UTC, skalish commented
I modeled the `dataset.create` function on the similar `attribute.create` function in that

1. The dataset is created in Tamr by calling `POST /v1/datasets`
2. The `Dataset` object is created by calling `GET /v1/datasets/{datasetId}` and deserializing the result

In both cases, I think the response from 1 contains the JSON necessary to create the `Dataset`.  Is there value in making two calls rather one here?  Maybe in some sense ensuring that the new dataset can be retrieved with `GET`.

2020-09-03 12:57 UTC, pcattori requested changes

2020-09-03 12:57 UTC, pcattori commented on tamr_client/dataset/_dataset.py
> +
For handling "already exists" errors, we can try to match on the response text to distinguish that error from other 400 errors:

```suggestion
if r.status_code == 400 and f'Dataset "{name}" already exists' in r.text:
    raise AlreadyExists(name)
```

Even if the server changes its error codes for "already exists" upstream, we will still at least catch any errors via `response.successful` on the next line.

2020-09-03 13:51 UTC, pcattori approved these changes
LGTM

Minor nit about test data

2020-09-03 13:51 UTC, pcattori commented on tests/tamr_client/fake_json/dataset/test_dataset/test_create_dataset_already_exists.json
> +                "message": "Dataset \"tc test dataset\" already exists"
nit: should this be:

```suggestion
                "message": "Dataset \"new dataset\" already exists"
```

2020-09-03 13:53 UTC, skalish commented on tests/tamr_client/fake_json/dataset/test_dataset/test_create_dataset_already_exists.json
> +                "message": "Dataset \"tc test dataset\" already exists"
Will change, just a minute.

2020-09-03 13:54 UTC, skalish commented
> I modeled the `dataset.create` function on the similar `attribute.create` function in that
> 
> 1. The dataset is created in Tamr by calling `POST /v1/datasets`
> 2. The `Dataset` object is created by calling `GET /v1/datasets/{datasetId}` and deserializing the result
> 
> In both cases, I think the response from 1 contains the JSON necessary to create the `Dataset`. Is there value in making two calls rather one here? Maybe in some sense ensuring that the new dataset can be retrieved with `GET`.

@pcattori any thoughts on this before merging?

2020-09-03 14:43 UTC, pcattori commented
> > I modeled the `dataset.create` function on the similar `attribute.create` function in that
> > 
> > 1. The dataset is created in Tamr by calling `POST /v1/datasets`
> > 2. The `Dataset` object is created by calling `GET /v1/datasets/{datasetId}` and deserializing the result
> > 
> > In both cases, I think the response from 1 contains the JSON necessary to create the `Dataset`. Is there value in making two calls rather one here? Maybe in some sense ensuring that the new dataset can be retrieved with `GET`.
> 
> @pcattori any thoughts on this before merging?

I think its conceptually simpler to always get the data via GET. If we run into perf issues, we can always change this since its an implementation detail not exposed to the end user.

2020-09-03 14:43 UTC, merged